server:
  port: 31001
spring:
  application:
    name: xc‐service‐manage‐cms
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: xc
  freemarker:
    cache: false  #关闭模板缓存
    settings:
      template_update_delay: 0  # 每0秒刷新一下页面，便于开发